[[news]]
date = "2026-04"
content = "Our [paper](https://doi.org/10.1016/j.socscimed.2026.119006) on financial assets and cardiometabolic risk has been published in *Social Science & Medicine*."

[[news]]
date = "2026-03"
content = "I will be joining the Department of Sociology at the University of Virginia as a PhD student in Fall 2026!"
